[project]
name = "my-utils"
version = "0.1.0"
description = "Reusable math utility functions"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
